### ISSUE TITLE
@-webkit-keyframes @keyframes support

### ISSUE THREAD

**Issue by joseph-jja** [SlexAxton/css-colorguard#25]
Doing something like 

.foo.bar {
  position: relative;
  text-indent: -9999em;
  -webkit-transform: translateZ(0);
  -ms-transform: translateZ(0);
  transform: translateZ(0);
  @-webkit-keyframes secondary-circular-loader {
... more css 

does not work.  It seems that colorguard does not parse the @- prefix for webkit, firefox or ms ( although ms is dropping that prefix ) nor does it support @keyframes erroring our with a line number and column number where the column number happens to be the @ symbol.  This is valid CSS.

There was an error processing the CSS.
Error: undefined:9060:3: missing '}'

**Comment by SlexAxton** [comment]
Parsing would be a bug in our upstream dependency in rework. It's possible that they've fixed this by now though.

**Comment by joseph-jja** [comment]
It does not look like this has been fixed in rework. They depend on css :(

**Comment by SlexAxton** [comment]
This is fixed now that we depend on PostCSS instead of rework. Thanks to @ben-eb
