### ISSUE TITLE
Error and Warning output

### ISSUE THREAD

**Issue by XOP** [SlexAxton/css-colorguard#28]
I'm experiencing strange output, something like

```
Running "colorguard:files" (colorguard) task
Warning: undefined:708:90: property missing ':' Use --force to continue.

Aborted due to warnings.
```

Even if I target single file, it's impossible to detect typo in this fragment.

I suggest either fixing or providing more clear output.

**Comment by SlexAxton** [comment]
Is this issue valid still @XOP ? Or did you close it for some reason?

Thanks!

**Comment by XOP** [comment]
Hi @SlexAxton!
This is valid, however I suggested it refers to the grunt-colorguard plugin, so I moved question there.
If you have any thoughts, it would be if you share.
I'm thinking about some specific rules like 
```
::-webkit-input-placeholder {color: #999;}
```
can cause the error, but anyway the task shouldn't just drop out.

**Comment by SlexAxton** [comment]
Ah. This is a problem with `reworkcss`. It was more or less abandoned and lots of these edge cases never made their way in.

We pushed a 1.x version of colorguard yesterday that moves it over to PostCSS, which means it can handle this. You just need grunt-colorguard to update their dependency (which includes a few small API integration changes).

**Comment by XOP** [comment]
That certainly makes sense!

Thanks, I'll pass this to grunt-colorguard developers.
