### ISSUE TITLE
whitelist ignores short HEX values

### ISSUE THREAD

**Issue by XOP** [SlexAxton/css-colorguard#30]
this will work
```
['#f7f7f7', '#ffffff']
```

this will not
```
['#f7f7f7', '#fff']
```

**Comment by XOP** [comment]
what's more
```
227:3   ‼  #000 collides with #000000 (31:29) [css-colorguard]
243:3   ‼  #000 collides with #000000 (31:29) [css-colorguard]
```
:disappointed:

**Comment by ben-eb** [comment]
I quite like that actually. It ensures that you define your hex colours consistently. :smile:

**Comment by XOP** [comment]
@ben-eb well, kinda :)
My implied stack finally worked with such "genuine" whitelist:
```
#ffffff #ffffff
#000000 #000000 
```
it's my format in css file, it's transformed into arrays collection on fly

**Comment by ben-eb** [comment]
You can use https://github.com/SlexAxton/css-colorguard#allowequivalentnotation to suppress warnings for equivalent colour definitions now.
