### ISSUE TITLE
whitelist ignores rgba values

### ISSUE THREAD

**Issue by XOP** [SlexAxton/css-colorguard#31]
RGBA values are very important in modern CSS, so they should be respected accordingly. 
Current whitelist is not applied*
```
['#000000', 'rgba(0,0,0,0.5)']
```
\* can't use short hex value due to https://github.com/SlexAxton/css-colorguard/issues/30

**Comment by ai** [comment]
@ben-eb do you need help here? I could find newbie developers :)

**Comment by kbytin** [comment]
I think the best solution is add config fo alpha colors, may be with limits.

like  no more then 20% : 

#000000 and rgba (0, 0, 0, 0.85)  - ok
#000000 and rgba (0, 0, 0, 0.75)  - error

**Comment by ben-eb** [comment]
I haven't the time to work on alpha transparency just yet, of course pull requests are welcome. This is the same issue as https://github.com/SlexAxton/css-colorguard/issues/32 right?

**Comment by ai** [comment]
@ben-eb yeap, I think they are same
