### ISSUE TITLE
Alternative to pipetteur (which uses one-color)?

### ISSUE THREAD

**Issue by davidtheclark** [SlexAxton/css-colorguard#36]
cf. https://github.com/stylelint/stylelint/issues/891

pipetteur relies one one-color, which does not run in environments that don't support eval, like Atom --- meaning the additional dependency of css-colorguard in stylelint breaks Atom's linter-stylelint.

It sounds like one-color is not going to be able to fix this (https://github.com/One-com/one-color/issues/22). So I wonder if there's another way for css-colorguard to get the information it needs. 

Were there any viable alternatives you ran across while originally developing the plugin? Or did you decide that pipetteur was really and uniquely necessary?

**Comment by SlexAxton** [comment]
Initially I only supported very naive color declarations. I don't think I saw anything else that did what pipetteur does (parse and normalize colors across all possible declaration types).

I'd be happy to take a PR switching it over to a compatible, but different tool.

**Comment by jeddy3** [comment]
Can we achieve the same with [`postcss-value-parser`](https://github.com/TrySound/) (similar to how we do in [`color-named`](https://github.com/stylelint/stylelint/blob/master/src/rules/color-named/index.js)) and [`color`](https://www.npmjs.com/package/color)?

**Comment by Munter** [comment]
We've talked it over a bit amongst the one-color contributors. And we believe it's worth dropping the original goal of minimal file size to make the library work in this case and others that block eval. We'll give the rewrite a shot on monday, and if we succeed I'll release an updated dependency chain that should fix this breakage.

**Comment by Munter** [comment]
One-color v3.0.0 now runs without eval. Pipetteur has been updated to 2.0.0 to use the updated version. This should solve the problem

**Comment by davidtheclark** [comment]
Thanks for the heads up, @Munter.
