### ISSUE TITLE
Consider removing preferGlobal flag

### ISSUE THREAD

**Issue by billyjanitsch** [SlexAxton/css-colorguard#42]
Is there any particular reason that the `preferGlobal` flag is [enabled in the project's package.json](https://github.com/SlexAxton/css-colorguard/blob/master/package.json#L6)? I understand that `colorguard` ships with a CLI, so a user may want to install it globally, but given that it also includes a node API, it's strange to get the `prefer global colorguard@1.1.1 should be installed with -g` npm warning on perfectly valid (local) installs.

Happy to submit a PR removing the flag.

**Comment by ben-eb** [comment]
I am 👍 for removing this. @SlexAxton?

**Comment by SlexAxton** [comment]
Yep. Go for it.

**Comment by billyjanitsch** [comment]
Great, thanks!
