### ISSUE TITLE
Option to ignore node_modules, other file globs? 

### ISSUE THREAD

**Issue by jfeldstein** [SlexAxton/css-colorguard#44]
My build complains because I use React-Select. 

Their [styles don't pass colorguard's test](https://github.com/JedWatson/react-select/issues/1012). 

As is, I have no way to say "no, don't lint my 3rd party libraries" or "ignore specific files". 

I think `ignoreFiles: /node_modules/` should be an option, and `/node_modules/` should be the default value. I'm [not the only person](https://github.com/JedWatson/react-select/issues/1012#issuecomment-224339527) who thinks so.

**Comment by ben-eb** [comment]
I recommend that you use https://github.com/tsm91/postcss-filter-stream for this purpose, doesn't make sense to add an option here.
