### ISSUE TITLE
Clarification of ignore option

### ISSUE THREAD

**Issue by benfrain** [SlexAxton/css-colorguard#48]
Firstly, what a a great bit of functionality this is. Thanks all for the work that's gone in to this. It's going to solve a few problems for me 👍 

Regarding the ignore option, am I correct in assuming that given an array like this:

````
"ignore": ["#444","#414141","#404040","#393939","#333","#303030","#222","#373737","#3D3D3D","#D2D2D2","#C4C4C4","#D3D3D3"]
````

Then comparisons with any different colours in the codebase against any of those 'ignore' values will be ignored?

So, say with a `threshold` of 2, if I have a value of `#424242` in the CSS, it won't get flagged as a warning because we have `#414141` in the ignore list, which is the thing it would ordinarily clash against. Is that correct?

**Comment by SlexAxton** [comment]
I think that's correct. More specifically it's the exact colors that when found in your css that won't throw an error under any circumstances, regardless of thresholds or anything like that. It's a decently big hammer since it's a global list.

**Comment by benfrain** [comment]
Ok. Thanks :)
