### ISSUE TITLE
Reporting as colliding with variable name

### ISSUE THREAD

**Issue by andreicek** [SlexAxton/css-colorguard#49]
When a variable name is used to define a color, and that variable name contains an actual color (red, gray, etc.) it is reported as colliding.

Example:

```
$base-warm-grey-color: #808080;
```

will report: `css-colorguard: (...): grey collides with #808080`

**Comment by Twilrom** [comment]
I assume you're using postcss-advanced-variables? Just put colorguard after that and it should work.
