### ISSUE TITLE
please publish a new release to NPM

### ISSUE THREAD

**Issue by thisconnect** [SlexAxton/css-colorguard#50]
Installing stylelint prints this message

```
npm WARN prefer global colorguard@1.2.0 should be installed with -g
```

https://github.com/SlexAxton/css-colorguard/commit/861d194dd0caa6538cd16d89618b60d949b6a216

related https://github.com/SlexAxton/css-colorguard/issues/42

**Comment by jcrben** [comment]
bump @SlexAxton

**Comment by SlexAxton** [comment]
done, thanks for the bump.
